name: goshi 

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: [goshi]

    strategy:
      matrix:
        node-version: [v16.13.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        #cache: 'npm'
    - run: npm i
    #- run: cp /home/prodrunner/env/9lives.env .
    - run: npm run build
